# Generated by Django 6.0.3 on 2026-03-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
    ]
